# Algoritmos de Otimização - Calendários de Voos

## Representação do problema

Vamos definir uma estrutura para representar os voos em um mapa (dicionário):

voos(k, v), onde:

- k = oridem, destino
- v = hora de saída, hora de chegada, preço

Lembrnado que:

- FCO -> Roma
- LIS -> Lisboa
- MAD -> Madrid
- CDG -> Paris
- DUB -> Dublin
- BRU -> Bruxelas
- LHR -> Londres


exemplo:

```
voos {('BRU', 'FCO'): ['15:44', '18:55', 382]}
print(voos[('BRU', 'FCO')])
print(voos[('BRU', 'FCO')])[0], print(voos[('BRU', 'FCO')])[1]

```



In [1]:
# essa base possui 10 voos de ida de cada cidade para ROMA e 10 voos de volta
# de ROMA para cada cidade de origem

voos = {} #cria o mapa (dicionário)

for linha in open('voos.txt'):
  #print(linha)
  #print(linha.split(','))

  #criamos as 5 variáveis para nosso mapa, separando os dados por ','
  origem, destino, saida, chegada, preco = linha.split(',')

  #geração de um vetor com as chaves do mapa:
  voos.setdefault((origem, destino), [])

  #acrescenta os dados no mapa pelas chaves:
  voos[(origem, destino)].append([saida, chegada, int(preco)])

In [2]:
# apenas um teste
# repare que gerou-se um mapa com as chaves "origem", "destino" (únicas) e com
# todos os voos deisponíveis para este trecho
voos

{('FCO', 'LIS'): [['6:19', '8:13', 239]],
 ('LIS', 'FCO'): [['6:11', '8:31', 249],
  ['7:39', '10:24', 219],
  ['9:15', '12:03', 99],
  ['11:08', '13:07', 175],
  ['12:18', '14:56', 172],
  ['13:37', '15:08', 250],
  ['15:03', '16:42', 135],
  ['16:51', '19:09', 147],
  ['18:12', '20:17', 242],
  ['20:05', '22:06', 261]],
 ('FCO', 'LIS'): [['8:04', '10:59', 136],
  ['9:31', '11:43', 210],
  ['11:07', '13:24', 171],
  ['12:31', '14:02', 234],
  ['14:05', '15:47', 226],
  ['15:07', '17:21', 129],
  ['16:35', '18:56', 144],
  ['18:25', '20:34', 205],
  ['20:05', '21:44', 172]],
 ('FCO', 'MAD'): [['6:03', '8:43', 219],
  ['7:50', '10:08', 164],
  ['9:11', '10:42', 172],
  ['10:33', '13:11', 132],
  ['12:08', '14:47', 231],
  ['14:19', '17:09', 190],
  ['15:04', '17:23', 189],
  ['17:06', '20:00', 95],
  ['18:33', '20:22', 143],
  ['19:32', '21:25', 160]],
 ('MAD', 'FCO'): [['6:05', '8:32', 174],
  ['8:25', '10:34', 157],
  ['9:42', '11:32', 169],
  ['11:01', '12:39', 260],
  ['12:44', '

In [3]:
voos['FCO', 'DUB']

[['6:39', '8:09', 86],
 ['8:23', '10:28', 149],
 ['9:58', '11:18', 130],
 ['10:33', '12:03', 74],
 ['12:08', '14:05', 142],
 ['13:39', '15:30', 74],
 ['15:25', '16:58', 62],
 ['17:03', '18:03', 103],
 ['18:24', '20:49', 124],
 ['19:58', '21:23', 142]]

In [4]:
voos['DUB', 'FCO']

[['6:17', '8:26', 89],
 ['8:04', '10:11', 95],
 ['9:45', '11:50', 172],
 ['11:16', '13:29', 83],
 ['12:34', '15:02', 109],
 ['13:40', '15:37', 138],
 ['15:27', '17:18', 151],
 ['17:11', '18:30', 108],
 ['18:34', '19:36', 136],
 ['20:17', '22:22', 102]]

In [5]:
voos['FCO', 'LIS'][7][2]

205

In [6]:
pessoas = [('Portugês', 'LIS'), # Lisboa - 0 1
           ('Espanhol', 'MAD'), # Madrid - 2 3
           ('Francês', 'CDG'),  # Paris  - 4 5
           ('Irlandês', 'DUB'), # Dublin - 6 7
           ('Belga', 'BRU'),    # Bruxelas - 8 9
           ('Londrino', 'LHR')] # Londres - 10 11


In [7]:
pessoas[3]

('Irlandês', 'DUB')

In [8]:
pessoas[3][0]

'Irlandês'

In [9]:
destino = 'FCO' #Roma

Para os algoritmos funcionarem corretamente precisaremos representar uma "agenda"

Como temos 6 locais de origem e destino, então usaremos um vetor de 12 posições, sendo 6 voos de ida + 6 voos de volta. Uma ida e uma volta para cada viajante.

- pessoa1: ida, volta
- pessoa2: ida, volta
- ...


Lembre-se que a ORDEM das pessoas é: LISBOA, MADRID, PARIS, BRUXELAS, LONDRES

Por isso, usaremos uma representação assim no vetor exemplo):

```
[0] -> De LISBOA até ROMA -> VOO 1 (segundo voo da lista de voos)
[1] -> De ROMA até LISBOA -> VOO3 (quarto voo da lista de voos)
[2] -> De MADRID até ROMA -> VOO 6 (sétimo voo da listas de voos)
[3] -> De ROMA até Madrid -> VOO5 (sexto voo da lista de voos)
```


In [10]:
agenda = [5,2, 3,0, 7,3, 6,1, 4,2, 8,5] # quem montará a agenda é o próprio algoritmo
len(agenda)

12

In [11]:
voos['LIS', 'FCO']

[['6:11', '8:31', 249],
 ['7:39', '10:24', 219],
 ['9:15', '12:03', 99],
 ['11:08', '13:07', 175],
 ['12:18', '14:56', 172],
 ['13:37', '15:08', 250],
 ['15:03', '16:42', 135],
 ['16:51', '19:09', 147],
 ['18:12', '20:17', 242],
 ['20:05', '22:06', 261]]

In [12]:
voos['LIS', 'FCO'][5]

['13:37', '15:08', 250]

In [13]:
voos['FCO', 'LIS'][2]

['11:07', '13:24', 171]

## Função de impressão de uma agenda

In [14]:
from prettytable import PrettyTable # veja: https://pypi.org/project/prettytable/

# vamos criar uma forma de mostrar os resultados de uma agenda

def imprimir_voos(agenda):
  id_voo = -1
  preco_total = 0
  tabela = PrettyTable(['Pessoa', 'Origem', 'Destino', 'H.Saída', 'H.Chegada', 'Valor'])
  for i in range(len(agenda) // 2):
    nome = pessoas[i][0]
    origem = pessoas[i][1]
    id_voo += 1
    ida = voos[(origem, destino)][agenda[id_voo]]
    preco_total += ida[2]
    id_voo += 1
    volta = voos[(destino, origem)][agenda[id_voo]]
    preco_total += volta[2]

    tabela.add_row([nome, origem, destino, ida[0], ida[1], ida[2]])
    tabela.add_row([nome, destino, origem, volta[0], volta[1], volta[2]])
    if (i != (len(agenda) // 2) - 1):
      tabela.add_row(['-','-','-','-','-','-'])
  print(tabela)
  print(f'Valor total: {preco_total}')


In [15]:
agenda = [5,2, 3,0, 7,3, 8,1, 3,2, 3,5]
imprimir_voos(agenda)

+----------+--------+---------+---------+-----------+-------+
|  Pessoa  | Origem | Destino | H.Saída | H.Chegada | Valor |
+----------+--------+---------+---------+-----------+-------+
| Portugês |  LIS   |   FCO   |  13:37  |   15:08   |  250  |
| Portugês |  FCO   |   LIS   |  11:07  |   13:24   |  171  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Espanhol |  MAD   |   FCO   |  11:01  |   12:39   |  260  |
| Espanhol |  FCO   |   MAD   |   6:03  |    8:43   |  219  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Francês  |  CDG   |   FCO   |  17:07  |   20:04   |  291  |
| Francês  |  FCO   |   CDG   |  11:08  |   14:38   |  262  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Irlandês |  DUB   |   FCO   |  18:34  |   19:36   |  136  |
| Irlandês |  FCO   |   DUB   |   8:23  |   10:28   |  149  |
|    -     |   -    |    -    |    -    |     -     |   -   |
|  Belga   |  BRU   |   FCO   |  10:30  |   14:57   |  290  |
|  Belga

In [16]:
# apenas para ilustrar: quantidade total de combinações para essa solução
10**12

1000000000000

 ## Fitness Function (função de custo)

 Serve para verificar se uma solução é boa ou não. Precisamos, em algoritmos de otimização, criar nossa própria função de custo. Cada problema terá sua função de custo específica.

 Possui praticamente o mesmo código que usamos para imprimir a agenda, entretanto vamos considerar apenas o valor total das passagens (neste caso) que é o que vamos otimizar (minimizar custos)

In [17]:
def fitness_function(agenda):
  id_voo = -1
  preco_total = 0
  for i in range(len(agenda) // 2):
    origem = pessoas[i][1]
    id_voo += 1
    ida = voos[(origem, destino)][agenda[id_voo]]
    preco_total += ida[2]
    id_voo += 1
    volta = voos[(destino, origem)][agenda[id_voo]]
    preco_total += volta[2]

  return preco_total

In [18]:
# exemplo
agenda = [3,2, 3,5, 7,3, 0,1, 3,2, 3,5]
fitness_function(agenda)

2437

In [19]:
import six
import sys
sys.modules['sklearn.externals.six'] = six
import mlrose

In [20]:
fitness = mlrose.CustomFitness(fitness_function)

In [21]:
# Trabalharemos com valores discretos (inteiros)
# Parâmetros utilizados no problema:
# - lenght: Tamanho da solução
# - função: Nossa função de fitness
# - maximize: que tipo de solução queremos: True refere-se aos maiores; False aos menores
# - max_val: a quantidade de voos que temos (valor máximo de cada posição na solução)

problema = mlrose.DiscreteOpt(length=12, fitness_fn=fitness, maximize=False, max_val=10)

## Hill Climb

In [ ]:
# o parâmetro "random_state" representa como é gerado o estado inicial
melhor_solucao, melhor_custo = mlrose.hill_climb(problema, random_state=1)

In [ ]:
print(melhor_solucao)
print(melhor_custo)

[2 6 5 7 8 1 3 6 0 2 9 1]
1566.0


In [ ]:
imprimir_voos(melhor_solucao)

+----------+--------+---------+---------+-----------+-------+
|  Pessoa  | Origem | Destino | H.Saída | H.Chegada | Valor |
+----------+--------+---------+---------+-----------+-------+
| Portugês |  LIS   |   FCO   |   9:15  |   12:03   |   99  |
| Portugês |  FCO   |   LIS   |  15:07  |   17:21   |  129  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Espanhol |  MAD   |   FCO   |  14:22  |   16:32   |  126  |
| Espanhol |  FCO   |   MAD   |  17:06  |   20:00   |   95  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Francês  |  CDG   |   FCO   |  18:23  |   21:35   |  134  |
| Francês  |  FCO   |   CDG   |   8:23  |   11:07   |  143  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Irlandês |  DUB   |   FCO   |  11:16  |   13:29   |   83  |
| Irlandês |  FCO   |   DUB   |  15:25  |   16:58   |   62  |
|    -     |   -    |    -    |    -    |     -     |   -   |
|  Belga   |  BRU   |   FCO   |   6:12  |   10:22   |  230  |
|  Belga

## Simulated Annealing

In [ ]:
from mlrose.neural import GeomDecay

melhor_solucao, melhor_custo = mlrose.simulated_annealing(problema,
                                                          schedule=mlrose.decay.GeomDecay(init_temp=1000000),
                                                          random_state=1)


print(melhor_solucao)
print(melhor_custo)

[2 9 5 3 8 1 1 5 0 2 9 5]
1690.0


In [ ]:
imprimir_voos(melhor_solucao)

+----------+--------+---------+---------+-----------+-------+
|  Pessoa  | Origem | Destino | H.Saída | H.Chegada | Valor |
+----------+--------+---------+---------+-----------+-------+
| Portugês |  LIS   |   FCO   |  15:03  |   16:42   |  135  |
| Portugês |  FCO   |   LIS   |   8:04  |   10:59   |  136  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Espanhol |  MAD   |   FCO   |  14:22  |   16:32   |  126  |
| Espanhol |  FCO   |   MAD   |  17:06  |   20:00   |   95  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Francês  |  CDG   |   FCO   |  19:53  |   22:21   |  173  |
| Francês  |  FCO   |   CDG   |  15:23  |   18:49   |  150  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Irlandês |  DUB   |   FCO   |  11:16  |   13:29   |   83  |
| Irlandês |  FCO   |   DUB   |  10:33  |   12:03   |   74  |
|    -     |   -    |    -    |    -    |     -     |   -   |
|  Belga   |  BRU   |   FCO   |  13:54  |   18:02   |  294  |
|  Belga

In [ ]:
help(mlrose.simulated_annealing)

Help on function simulated_annealing in module mlrose.algorithms:

simulated_annealing(problem, schedule=<mlrose.decay.GeomDecay object at 0x7f39484036a0>, max_attempts=10, max_iters=inf, init_state=None, curve=False, random_state=None)
    Use simulated annealing to find the optimum for a given
    optimization problem.
    
    Parameters
    ----------
    problem: optimization object
        Object containing fitness function optimization problem to be solved.
        For example, :code:`DiscreteOpt()`, :code:`ContinuousOpt()` or
        :code:`TSPOpt()`.
    schedule: schedule object, default: :code:`mlrose.GeomDecay()`
        Schedule used to determine the value of the temperature parameter.
    max_attempts: int, default: 10
        Maximum number of attempts to find a better neighbor at each step.
    max_iters: int, default: np.inf
        Maximum number of iterations of the algorithm.
    init_state: array, default: None
        1-D Numpy array containing starting state for 

## Algoritmo Genético

In [ ]:
# parâmetros que utilizaremos

# pop_size: tamanho da população inicial (será gerada aleatóriamente)
# mutation_prob = probabilidade de ocorrer uma mutação durante a evolução (em porcentagem)
# max_iter = critério de parada - opcional (número máximo de gerações a serem geradas)

melhor_solucao, melhor_custo = mlrose.genetic_alg(problema, pop_size=10000,
                                                  mutation_prob=0.1, random_state=1)

print(melhor_solucao)
print(melhor_custo)

[2 2 6 3 8 9 0 0 0 3 5 5]
1857.0


In [ ]:
imprimir_voos(melhor_solucao)

+----------+--------+---------+---------+-----------+-------+
|  Pessoa  | Origem | Destino | H.Saída | H.Chegada | Valor |
+----------+--------+---------+---------+-----------+-------+
| Portugês |  LIS   |   FCO   |  16:51  |   19:09   |  147  |
| Portugês |  FCO   |   LIS   |  16:35  |   18:56   |  144  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Espanhol |  MAD   |   FCO   |  15:58  |   18:40   |  173  |
| Espanhol |  FCO   |   MAD   |  14:19  |   17:09   |  190  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Francês  |  CDG   |   FCO   |  18:23  |   21:35   |  134  |
| Francês  |  FCO   |   CDG   |  12:37  |   15:05   |  170  |
|    -     |   -    |    -    |    -    |     -     |   -   |
| Irlandês |  DUB   |   FCO   |   8:04  |   10:11   |   95  |
| Irlandês |  FCO   |   DUB   |  15:25  |   16:58   |   62  |
|    -     |   -    |    -    |    -    |     -     |   -   |
|  Belga   |  BRU   |   FCO   |   6:12  |   10:22   |  230  |
|  Belga